version: "3.9"

services:

  flask:
    build: ./flask_server
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    networks:
      - ollama-network
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-network

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
            

networks:
  ollama-network:
    driver: bridge

volumes:
  ollama-data:
